moive_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie_app/urls.py
from django.urls import path
from. import views

app_name = 'movieapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('details/<int:movie_id>/', views.details, name='details'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('search', views.search, name='search')

]

movie_app/models.py
from django.db import models
from django.urls import reverse


class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    img = models.ImageField(upload_to='movies_image')



    def __str__(self):
        return self.name

movie_app/forms.py
from .models import Movie
from django import forms

class FormsMovies(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','img']

movie_app/views.py
from django.db.models import Q
from django.shortcuts import render, HttpResponse, redirect
from.models import Movie
from.forms import FormsMovies



def home(request):
    movie = Movie.objects.all()
    context ={
        'movie_list': movie
    }
    return render(request, 'movie.html', context)


def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def add(request):
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,img=img)
        movie.save()

    return render(request, 'add.html')


def update(request,id):
    movie = Movie.objects.get(id=id)
    form= FormsMovies(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':movie,'form':form})


def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')


def search(request):
    query = None
    product = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        product = Movie.objects.all().filter(Q(name__contains=query)|Q(desc__contains=query))
        return render(request,'search.html',{'query':query,'product':product})

templates/add.html
{% extends 'base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
    <div class="card mt-5 px-4  py-4 rounded-2 shadow" style="width:500px;height:450px;background-color:#F4F8F9;">
        <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 style="text-align:center">Add Movies</h3><br>
            <input type="text" name="name" placeholder="enter movie name"><br><br>
            <h6 class="text-black-50">write description :</h6>
            <textarea rows="6" cols="60" name="desc"></textarea><br><br>
            <input type="file" name="img"><br>
            <input class="rounded-pill px-4 bg-secondary" style="margin-top:35px;margin-left:160px;" type="submit">

        </form>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#53c68c">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Movies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" method="get" action="{% url 'movieapp:search' %}">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
  html,body {
  height: 100%;

}
    </style>
</head>
<body style="">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Movies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-outline-primary" href="{% url 'movieapp:add' %}">Add</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'movieapp:search' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container w-25" style="height:250px">
    <div class="card w-100 h-75 m-4 shadow" style="border-radius:10px;border-color:#809fff;border-width:5px;background-color:#F4F8F9">
        <form method="post">
            {% csrf_token %}
            <p style="margin-top:15px;margin-left:10px">are you sure ? do you want to delete this?</p>
            <input class="btn btn-danger" type="submit" style="margin-left:120px;margin-top:50px">
        </form>
    </div>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="card">
            <img src="{{ movie.img.url }}">
        </div>
        <div class="card-body">
            <p class="card-title">{{movie.name}}</p>
            {{movie.desc}}<br>
            <div class="d-flex justify-content-center">
            <a href="{% url 'movieapp:update' movie.id %}" class="btn btn-warning mx-2">update</a>
            <a href="{% url 'movieapp:delete' movie.id %}" class="btn btn-danger mx-2">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container d-flex justify-content-center ">
    <div class="ps-2 m-3 border border-5 border-primary" style="width:400px;border-radius:5px;border-color:#5cd6d6;background-color:#E9F1F3">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <div style="text-align:center">
            <input class="btn btn-secondary m-2" type="submit">
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/movie.html
{% extends 'base1.html' %}
{% block content %}
<div class="container-fluid" style="background-image: linear-gradient(#d1e0e0,#3e5b5b,#486a6a);">
    <div class="row" style="margin-left:25px">
        {% for m in movie_list %}
        <div class="col-3">
            <div class="card my-5" style="width: 18rem; height:350px;">
              <a href="{% url 'movieapp:details' m.id %}"><img src="{{ m.img.url }}" class="card-img-top " style="height:250px;"></a>
              <div class="card-body">
                <a class="card-title" href="{% url 'movieapp:details' m.id %}">{{m.name}}</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base1.html' %}
{% block content %}
<div class="container-fluid" style="background-image: linear-gradient(#d1e0e0,#3e5b5b,#486a6a);">
    <div class="row" style="margin-left:25px">
        {% for p in product %}
        <div class="col-3">
            <div class="card my-5" style="width: 18rem; height:350px;">
              <a href="/details/{{p.name}}"><img src="{{ p.img.url }}" class="card-img-top " style="height:250px;"></a>
              <div class="card-body">
                <a class="card-title" href="/details/{{p.name}}">{{p.name}}</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}